# Generated by Django 3.1.6 on 2021-03-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocodingsettings',
            options={'verbose_name_plural': 'Reverse Geocoding Settings'},
        ),
    ]
