# Generated by Django 3.1.6 on 2021-02-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_no',
            field=models.IntegerField(blank=True, help_text='Optional', null=True, verbose_name='VAT No.'),
        ),
    ]
