# Generated by Django 3.1.6 on 2021-02-09 14:48

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210209_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [83.98, 28.2], 'cursor_style': 'pointer', 'fullscreen_button': False, 'geocoder': True, 'marker_color': 'red', 'navigation_buttons': True, 'placeholder': 'Pick a location on map below', 'readonly': True, 'rotate': False, 'track_location_button': True, 'zoom': 11}),
        ),
    ]
