# Generated by Django 3.1.6 on 2021-03-09 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_creditpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='amount',
            field=models.FloatField(help_text='Enter amount greater than zero.'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_type', models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit'), ('CH', 'Cheque'), ('CP', 'Credit Payment')], default='CA', max_length=2)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', related_query_name='payment_history', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
