# Generated by Django 3.1.6 on 2021-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210309_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'verbose_name': 'Due Payment', 'verbose_name_plural': 'Due Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit'), ('CH', 'Cheque'), ('DP', 'Due Payment')], default='CA', max_length=2),
        ),
    ]
