# Generated by Django 3.1.6 on 2021-03-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210309_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Sale Location')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sale_location',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown or create a new location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.salelocation'),
        ),
    ]
