# Generated by Django 3.1.6 on 2021-02-23 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields
import mapbox_location_field.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20210209_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, unique=True, verbose_name='Egg Type')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [83.98, 28.2], 'cursor_style': 'pointer', 'fullscreen_button': False, 'geocoder': True, 'marker_color': 'red', 'navigation_buttons': True, 'placeholder': 'Pick a location on map below', 'readonly': True, 'rotate': False, 'track_location_button': True, 'zoom': 11})),
                ('signature', jsignature.fields.JSignatureField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='In Crate')),
                ('egg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.eggtype')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', related_query_name='sales', to='sales.sale', verbose_name='Sale Item')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CA', 'Cash'), ('CH', 'Cheque'), ('CR', 'Credit')], default='CA', max_length=2)),
                ('amount', models.FloatField(default=0.0)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payments', to='sales.sale', verbose_name='Payment')),
            ],
        ),
    ]
