# Generated by Django 3.1.6 on 2021-03-10 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_payment_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='salesman',
        ),
        migrations.AddField(
            model_name='sale',
            name='salesman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesman', related_query_name='salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
