# Generated by Django 3.1.6 on 2021-03-10 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_auto_20210310_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesman', related_query_name='salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
