# Generated by Django 3.1.6 on 2021-03-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210312_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_location',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown or create a new location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salelocation'),
        ),
    ]
