# Generated by Django 3.1.6 on 2021-03-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210309_2208'),
        ('sales', '0007_auto_20210312_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', related_query_name='sale', to='customer.customer', verbose_name='Customer'),
        ),
    ]
