# Generated by Django 3.1.6 on 2021-03-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210324_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_location',
        ),
        migrations.DeleteModel(
            name='SaleLocation',
        ),
    ]
