# Generated by Django 3.1.6 on 2021-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210324_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='descriptive_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descriptive Location'),
        ),
    ]
