# Generated by Django 3.1.6 on 2021-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_descriptive_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Sale Item Amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='descriptive_location',
            field=models.CharField(blank=True, help_text='Eg: Parshyang, Malepatan', max_length=100, null=True, verbose_name='Descriptive Location'),
        ),
    ]
